spring:
  security:
    oauth2:
      resourceserver:
        jwt:
#          issuer-uri: http://keycloak:8080/realms/cab-aggregator-realm
          jwk-set-uri: http://keycloak:8080/realms/cab-aggregator-realm/protocol/openid-connect/certs
  application:
    name: driver-service
  datasource:
    driver-class-name: org.postgresql.Driver
    password: 12345
    username: postgres
    url: jdbc:postgresql://localhost:5432/driverdb
  jpa:
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  kafka:
    bootstrap-servers: kafka:29092
    consumer:
      properties:
        spring.json:
          trusted.packages: "*"
          type.mapping: DriverRequest:com.example.driverservice.dto.request.DriverRequest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      bootstrap-servers: kafka:29092
      group-id: driverGroup
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      bootstrap-servers: kafka:29092
      properties:
        spring.json.type.mapping: RideRequest:com.example.driverservice.dto.request.RideRequest
topic:
  name:
    driver: driver-available
    ride: driver-search
kafka:
  partitions:
    count: 5
  replicas:
    count: 1
server:
  port: 8085
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
  endpoints.web:
    base-path: /actuator
    exposure.include: 'prometheus, health'
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.request]": true
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true
jwt:
  auth:
    converter:
      resource-id: cab-aggregator-client
      principal-attribute: preferred_username
logging:
  level:
    org.springframework.security: DEBUG
